apiVersion: v1
kind: Service
metadata:
  name: cassandra-svc
  labels:
    run: cassandra-svc
spec:
  ports:
  - name: intra-node
    port: 7000
    protocol: TCP
  - name: tls-intra-node
    port: 7001
    protocol: TCP
  - name: jmx
    port: 7199
    protocol: TCP
  - name: cql
    port: 9042
    protocol: TCP
  selector:
    run: cassandra
