apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data
  labels:
    type: local
spec:
  storageClassName: localstorage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/ale/Documents/KUL/CSSE/Cloud/k8-scalar/operations/cassandra-cluster
/cassandra_data"